# Generated by Django 3.0.7 on 2020-06-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetRegistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
